from setuptools import setup

setup(
    name='python server',
    version='',
    packages=['venv.lib.python3.5.site-packages.pip', 'venv.lib.python3.5.site-packages.pip._vendor',
              'venv.lib.python3.5.site-packages.pip._vendor.idna',
              'venv.lib.python3.5.site-packages.pip._vendor.pytoml',
              'venv.lib.python3.5.site-packages.pip._vendor.certifi',
              'venv.lib.python3.5.site-packages.pip._vendor.chardet',
              'venv.lib.python3.5.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib',
              'venv.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.5.site-packages.pip._vendor.msgpack',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.5.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.pip._vendor.colorama',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.5.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.5.site-packages.pip._vendor.progress',
              'venv.lib.python3.5.site-packages.pip._vendor.requests',
              'venv.lib.python3.5.site-packages.pip._vendor.packaging',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.5.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.5.site-packages.pip._internal', 'venv.lib.python3.5.site-packages.pip._internal.req',
              'venv.lib.python3.5.site-packages.pip._internal.vcs',
              'venv.lib.python3.5.site-packages.pip._internal.utils',
              'venv.lib.python3.5.site-packages.pip._internal.models',
              'venv.lib.python3.5.site-packages.pip._internal.commands',
              'venv.lib.python3.5.site-packages.pip._internal.operations', 'venv.lib.python3.5.site-packages.idna',
              'venv.lib.python3.5.site-packages.pytz', 'venv.lib.python3.5.site-packages.numpy',
              'venv.lib.python3.5.site-packages.numpy.ma', 'venv.lib.python3.5.site-packages.numpy.ma.tests',
              'venv.lib.python3.5.site-packages.numpy.doc', 'venv.lib.python3.5.site-packages.numpy.fft',
              'venv.lib.python3.5.site-packages.numpy.fft.tests', 'venv.lib.python3.5.site-packages.numpy.lib',
              'venv.lib.python3.5.site-packages.numpy.lib.tests', 'venv.lib.python3.5.site-packages.numpy.core',
              'venv.lib.python3.5.site-packages.numpy.core.tests', 'venv.lib.python3.5.site-packages.numpy.f2py',
              'venv.lib.python3.5.site-packages.numpy.f2py.tests', 'venv.lib.python3.5.site-packages.numpy.tests',
              'venv.lib.python3.5.site-packages.numpy.compat', 'venv.lib.python3.5.site-packages.numpy.compat.tests',
              'venv.lib.python3.5.site-packages.numpy.linalg', 'venv.lib.python3.5.site-packages.numpy.linalg.tests',
              'venv.lib.python3.5.site-packages.numpy.random', 'venv.lib.python3.5.site-packages.numpy.random.tests',
              'venv.lib.python3.5.site-packages.numpy.testing', 'venv.lib.python3.5.site-packages.numpy.testing.tests',
              'venv.lib.python3.5.site-packages.numpy.testing._private',
              'venv.lib.python3.5.site-packages.numpy.distutils',
              'venv.lib.python3.5.site-packages.numpy.distutils.tests',
              'venv.lib.python3.5.site-packages.numpy.distutils.command',
              'venv.lib.python3.5.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python3.5.site-packages.numpy.matrixlib',
              'venv.lib.python3.5.site-packages.numpy.matrixlib.tests',
              'venv.lib.python3.5.site-packages.numpy.polynomial',
              'venv.lib.python3.5.site-packages.numpy.polynomial.tests', 'venv.lib.python3.5.site-packages.scipy',
              'venv.lib.python3.5.site-packages.scipy.io', 'venv.lib.python3.5.site-packages.scipy.io.arff',
              'venv.lib.python3.5.site-packages.scipy.io.arff.tests', 'venv.lib.python3.5.site-packages.scipy.io.tests',
              'venv.lib.python3.5.site-packages.scipy.io.matlab',
              'venv.lib.python3.5.site-packages.scipy.io.matlab.tests',
              'venv.lib.python3.5.site-packages.scipy.io.harwell_boeing',
              'venv.lib.python3.5.site-packages.scipy.io.harwell_boeing.tests',
              'venv.lib.python3.5.site-packages.scipy.odr', 'venv.lib.python3.5.site-packages.scipy.odr.tests',
              'venv.lib.python3.5.site-packages.scipy._lib', 'venv.lib.python3.5.site-packages.scipy._lib.tests',
              'venv.lib.python3.5.site-packages.scipy.misc', 'venv.lib.python3.5.site-packages.scipy.misc.tests',
              'venv.lib.python3.5.site-packages.scipy.stats', 'venv.lib.python3.5.site-packages.scipy.stats.tests',
              'venv.lib.python3.5.site-packages.scipy.linalg', 'venv.lib.python3.5.site-packages.scipy.linalg.tests',
              'venv.lib.python3.5.site-packages.scipy.signal', 'venv.lib.python3.5.site-packages.scipy.signal.tests',
              'venv.lib.python3.5.site-packages.scipy.signal.windows', 'venv.lib.python3.5.site-packages.scipy.sparse',
              'venv.lib.python3.5.site-packages.scipy.sparse.tests',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.eigen',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.eigen.arpack',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.eigen.arpack.tests',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.eigen.lobpcg',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.eigen.lobpcg.tests',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.tests',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.dsolve',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.dsolve.tests',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.isolve',
              'venv.lib.python3.5.site-packages.scipy.sparse.linalg.isolve.tests',
              'venv.lib.python3.5.site-packages.scipy.sparse.csgraph',
              'venv.lib.python3.5.site-packages.scipy.sparse.csgraph.tests',
              'venv.lib.python3.5.site-packages.scipy.cluster', 'venv.lib.python3.5.site-packages.scipy.cluster.tests',
              'venv.lib.python3.5.site-packages.scipy.fftpack', 'venv.lib.python3.5.site-packages.scipy.fftpack.tests',
              'venv.lib.python3.5.site-packages.scipy.ndimage', 'venv.lib.python3.5.site-packages.scipy.ndimage.tests',
              'venv.lib.python3.5.site-packages.scipy.spatial', 'venv.lib.python3.5.site-packages.scipy.spatial.tests',
              'venv.lib.python3.5.site-packages.scipy.special', 'venv.lib.python3.5.site-packages.scipy.special.tests',
              'venv.lib.python3.5.site-packages.scipy.special._precompute',
              'venv.lib.python3.5.site-packages.scipy.optimize', 'venv.lib.python3.5.site-packages.scipy.optimize._lsq',
              'venv.lib.python3.5.site-packages.scipy.optimize.tests',
              'venv.lib.python3.5.site-packages.scipy.optimize._trlib',
              'venv.lib.python3.5.site-packages.scipy.optimize._trustregion_constr',
              'venv.lib.python3.5.site-packages.scipy.optimize._trustregion_constr.tests',
              'venv.lib.python3.5.site-packages.scipy.constants',
              'venv.lib.python3.5.site-packages.scipy.constants.tests',
              'venv.lib.python3.5.site-packages.scipy.integrate',
              'venv.lib.python3.5.site-packages.scipy.integrate._ivp',
              'venv.lib.python3.5.site-packages.scipy.integrate.tests',
              'venv.lib.python3.5.site-packages.scipy.interpolate',
              'venv.lib.python3.5.site-packages.scipy.interpolate.tests',
              'venv.lib.python3.5.site-packages.scipy._build_utils', 'venv.lib.python3.5.site-packages.matlab',
              'venv.lib.python3.5.site-packages.matlab.engine', 'venv.lib.python3.5.site-packages.matlab._internal',
              'venv.lib.python3.5.site-packages.certifi', 'venv.lib.python3.5.site-packages.chardet',
              'venv.lib.python3.5.site-packages.chardet.cli', 'venv.lib.python3.5.site-packages.urllib3',
              'venv.lib.python3.5.site-packages.urllib3.util', 'venv.lib.python3.5.site-packages.urllib3.contrib',
              'venv.lib.python3.5.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.5.site-packages.urllib3.packages',
              'venv.lib.python3.5.site-packages.urllib3.packages.backports',
              'venv.lib.python3.5.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.5.site-packages.cloudant', 'venv.lib.python3.5.site-packages.dateutil',
              'venv.lib.python3.5.site-packages.dateutil.tz', 'venv.lib.python3.5.site-packages.dateutil.parser',
              'venv.lib.python3.5.site-packages.dateutil.zoneinfo', 'venv.lib.python3.5.site-packages.networkx',
              'venv.lib.python3.5.site-packages.networkx.tests', 'venv.lib.python3.5.site-packages.networkx.utils',
              'venv.lib.python3.5.site-packages.networkx.linalg', 'venv.lib.python3.5.site-packages.networkx.classes',
              'venv.lib.python3.5.site-packages.networkx.drawing', 'venv.lib.python3.5.site-packages.networkx.testing',
              'venv.lib.python3.5.site-packages.networkx.readwrite',
              'venv.lib.python3.5.site-packages.networkx.readwrite.json_graph',
              'venv.lib.python3.5.site-packages.networkx.algorithms',
              'venv.lib.python3.5.site-packages.networkx.algorithms.flow',
              'venv.lib.python3.5.site-packages.networkx.algorithms.tree',
              'venv.lib.python3.5.site-packages.networkx.algorithms.coloring',
              'venv.lib.python3.5.site-packages.networkx.algorithms.bipartite',
              'venv.lib.python3.5.site-packages.networkx.algorithms.community',
              'venv.lib.python3.5.site-packages.networkx.algorithms.operators',
              'venv.lib.python3.5.site-packages.networkx.algorithms.traversal',
              'venv.lib.python3.5.site-packages.networkx.algorithms.centrality',
              'venv.lib.python3.5.site-packages.networkx.algorithms.components',
              'venv.lib.python3.5.site-packages.networkx.algorithms.isomorphism',
              'venv.lib.python3.5.site-packages.networkx.algorithms.connectivity',
              'venv.lib.python3.5.site-packages.networkx.algorithms.approximation',
              'venv.lib.python3.5.site-packages.networkx.algorithms.assortativity',
              'venv.lib.python3.5.site-packages.networkx.algorithms.link_analysis',
              'venv.lib.python3.5.site-packages.networkx.algorithms.shortest_paths',
              'venv.lib.python3.5.site-packages.networkx.algorithms.node_classification',
              'venv.lib.python3.5.site-packages.networkx.generators', 'venv.lib.python3.5.site-packages.requests',
              'venv.lib.python3.5.site-packages.matplotlib', 'venv.lib.python3.5.site-packages.matplotlib.tri',
              'venv.lib.python3.5.site-packages.matplotlib.axes', 'venv.lib.python3.5.site-packages.matplotlib.cbook',
              'venv.lib.python3.5.site-packages.matplotlib.style', 'venv.lib.python3.5.site-packages.matplotlib.tests',
              'venv.lib.python3.5.site-packages.matplotlib.compat',
              'venv.lib.python3.5.site-packages.matplotlib.testing',
              'venv.lib.python3.5.site-packages.matplotlib.testing.jpl_units',
              'venv.lib.python3.5.site-packages.matplotlib.backends',
              'venv.lib.python3.5.site-packages.matplotlib.backends.qt_editor',
              'venv.lib.python3.5.site-packages.matplotlib.sphinxext',
              'venv.lib.python3.5.site-packages.matplotlib.sphinxext.tests',
              'venv.lib.python3.5.site-packages.matplotlib.projections', 'venv.lib.python3.5.site-packages.setuptools',
              'venv.lib.python3.5.site-packages.setuptools.extern',
              'venv.lib.python3.5.site-packages.setuptools._vendor',
              'venv.lib.python3.5.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.5.site-packages.setuptools.command',
              'venv.lib.python3.5.site-packages.mpl_toolkits.tests',
              'venv.lib.python3.5.site-packages.mpl_toolkits.mplot3d',
              'venv.lib.python3.5.site-packages.mpl_toolkits.axes_grid',
              'venv.lib.python3.5.site-packages.mpl_toolkits.axes_grid1',
              'venv.lib.python3.5.site-packages.mpl_toolkits.axisartist',
              'venv.lib.python3.5.site-packages.pkg_resources', 'venv.lib.python3.5.site-packages.pkg_resources.extern',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor',
              'venv.lib.python3.5.site-packages.pkg_resources._vendor.packaging'],
    url='https://github.com/vladbragoi/fingerprinting_server',
    license='',
    author='vlad',
    author_email='vlad.bragoi@gmail.com',
    description='', install_requires=['matlab', 'cloudant', 'networkx']
)
